### ISSUE TITLE
multiple shared modules

### ISSUE THREAD

**Issue by WispY** [portable-scala/sbt-crossproject#111]
Hello, I am trying to set up a cross JS/JVM project that also includes macros.

Is there any way to have two shared sub-projects? One for macro definitions (to be compiled before it's used) and one for shared code between JS and JVM?

This is a rough idea of what I am trying to achieve:
```
lazy val macros = (project in file("macros"))
lazy val shared = (project in file("shared")).dependsOn(macros)
lazy val js = (project in file("js")).dependsOn(macros, shared)
lazy val jvm = (project in file("jvm")).dependsOn(macros, shared)
```

Thanks in advance.

**Comment by sjrd** [comment]
Hello,

This looks like a question on using sbt-crossproject, rather than a bug report. The GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Gitter](https://gitter.im/scala-native/sbt-crossproject), where more than just the core developers can see and answer.

Thank you for your understanding.

**Comment by WispY** [comment]
Sorry, saw the label "question" and thought this would be appropriate place.
